shell fish

# Copy and paste with Ctrl+C and Ctrl+V
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# Cut (Kitty doesn't have a native 'cut' text concept, but this copies)
map ctrl+x copy_to_clipboard

# Select All (Kitty passes this to the shell, handled in Step 2)



# BEGIN_KITTY_THEME
# Afterglow
include current-theme.conf
background #131517
# END_KITTY_THEME

background_opacity 0.95
background_blur 32
confirm_os_window_close 0
font_size 12

# BEGIN_KITTY_FONTS
font_family      family="DejaVu Sans Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS





